services:
  postgres:
    container_name: postgres1
    image: postgres:16.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=awesomepass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=habutaso@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=awesomepgadmin
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres
  
  backend:
    container_name: backend
    build:
      context: back-end
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
  frontend:
    container_name: frontend
    build:
      context: front-end
    ports:
      - "3333:3333"
    depends_on:
      - postgres