services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=awesomepass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@example.com
      - PGADMIN_DEFAULT_PASSWORD=awesomepgadmin
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres
  
  # back-end:
  #   container_name: back-end
  #   build:
  #     context: back-end
  #     target: develop
  #   ports:
  #     - "3000:3000"
  #     - "4466:4466"
  #   environment:
  #     PRISMA_CONFIG: |
  #       port: 4466
  #       databases:
  #         default:
  #           connector: postgres
  #           host: postgres
  #           port: 5432
  #           user: user
  #           password: awesomepass
  #   volumes:
  #     - type: bind
  #       source: ./back-end
  #       target: /app
  #   depends_on:
  #     - postgres
  
  # front-end:
  #   container_name: front-end
  #   build:
  #     context: front-end
  #     target: develop
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - type: bind
  #       source: ./front-end
  #       target: /app
  #   depends_on:
  #     - postgres